[package]
name = "carbon-jito-protos"
version = "0.12.0"
edition = "2024"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
protobuf-src.workspace = true
tonic-prost-build.workspace = true
